// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcbid.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	grpcbid.proto

It has these top-level messages:
	GrpcBidReq
	GrpcBidRsp
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// 这里定义一个双向的服务， 通过用户名称来查询用户年纪
type GrpcBidReq struct {
	Req []byte `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (m *GrpcBidReq) Reset()                    { *m = GrpcBidReq{} }
func (m *GrpcBidReq) String() string            { return proto1.CompactTextString(m) }
func (*GrpcBidReq) ProtoMessage()               {}
func (*GrpcBidReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GrpcBidReq) GetReq() []byte {
	if m != nil {
		return m.Req
	}
	return nil
}

type GrpcBidRsp struct {
	Rsp []byte `protobuf:"bytes,1,opt,name=rsp,proto3" json:"rsp,omitempty"`
}

func (m *GrpcBidRsp) Reset()                    { *m = GrpcBidRsp{} }
func (m *GrpcBidRsp) String() string            { return proto1.CompactTextString(m) }
func (*GrpcBidRsp) ProtoMessage()               {}
func (*GrpcBidRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GrpcBidRsp) GetRsp() []byte {
	if m != nil {
		return m.Rsp
	}
	return nil
}

func init() {
	proto1.RegisterType((*GrpcBidReq)(nil), "proto.GrpcBidReq")
	proto1.RegisterType((*GrpcBidRsp)(nil), "proto.GrpcBidRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GrpcBid service

type GrpcBidClient interface {
	Comm(ctx context.Context, opts ...grpc.CallOption) (GrpcBid_CommClient, error)
}

type grpcBidClient struct {
	cc *grpc.ClientConn
}

func NewGrpcBidClient(cc *grpc.ClientConn) GrpcBidClient {
	return &grpcBidClient{cc}
}

func (c *grpcBidClient) Comm(ctx context.Context, opts ...grpc.CallOption) (GrpcBid_CommClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GrpcBid_serviceDesc.Streams[0], c.cc, "/proto.GrpcBid/Comm", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcBidCommClient{stream}
	return x, nil
}

type GrpcBid_CommClient interface {
	Send(*GrpcBidReq) error
	Recv() (*GrpcBidRsp, error)
	grpc.ClientStream
}

type grpcBidCommClient struct {
	grpc.ClientStream
}

func (x *grpcBidCommClient) Send(m *GrpcBidReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *grpcBidCommClient) Recv() (*GrpcBidRsp, error) {
	m := new(GrpcBidRsp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GrpcBid service

type GrpcBidServer interface {
	Comm(GrpcBid_CommServer) error
}

func RegisterGrpcBidServer(s *grpc.Server, srv GrpcBidServer) {
	s.RegisterService(&_GrpcBid_serviceDesc, srv)
}

func _GrpcBid_Comm_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpcBidServer).Comm(&grpcBidCommServer{stream})
}

type GrpcBid_CommServer interface {
	Send(*GrpcBidRsp) error
	Recv() (*GrpcBidReq, error)
	grpc.ServerStream
}

type grpcBidCommServer struct {
	grpc.ServerStream
}

func (x *grpcBidCommServer) Send(m *GrpcBidRsp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *grpcBidCommServer) Recv() (*GrpcBidReq, error) {
	m := new(GrpcBidReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GrpcBid_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GrpcBid",
	HandlerType: (*GrpcBidServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Comm",
			Handler:       _GrpcBid_Comm_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpcbid.proto",
}

func init() { proto1.RegisterFile("grpcbid.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2f, 0x2a, 0x48,
	0x4e, 0xca, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x72, 0x5c,
	0x5c, 0xee, 0x45, 0x05, 0xc9, 0x4e, 0x99, 0x29, 0x41, 0xa9, 0x85, 0x42, 0x02, 0x5c, 0xcc, 0x45,
	0xa9, 0x85, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x20, 0x26, 0xb2, 0x7c, 0x71, 0x01, 0x58,
	0xbe, 0xb8, 0x00, 0x2e, 0x5f, 0x5c, 0x60, 0x64, 0xcb, 0xc5, 0x0e, 0x95, 0x17, 0x32, 0xe2, 0x62,
	0x71, 0xce, 0xcf, 0xcd, 0x15, 0x12, 0x84, 0xd8, 0xa0, 0x87, 0x30, 0x57, 0x0a, 0x5d, 0xa8, 0xb8,
	0x40, 0x89, 0x41, 0x83, 0xd1, 0x80, 0x31, 0x89, 0x0d, 0x2c, 0x6e, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0xa0, 0xbb, 0xdc, 0xe5, 0x9d, 0x00, 0x00, 0x00,
}
